// <auto-generated />
using System;
using EmailService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmailService.Infrastructure.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    partial class EmailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailService.Domain.Entities.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MessageErreur")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("EmailService.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Corps = "Bonjour {NomCandidat},\n\nNous avons bien reçu votre candidature pour le poste de {Poste}.\n\nVotre dossier sera étudié avec attention et nous vous contacterons prochainement pour vous tenir informé(e) de la suite du processus.\n\nNous vous remercions de l'intérêt que vous portez à notre entreprise.\n\nCordialement,\n{NomEntreprise}",
                            EstActif = true,
                            Sujet = "Confirmation de votre candidature – {Poste}",
                            Type = "ConfirmationPostulation"
                        },
                        new
                        {
                            Id = 2,
                            Corps = "Bonjour {NomCandidat},\n\nNous avons le plaisir de vous confirmer votre entretien pour le poste de {Poste}.\n\nDate : {DateEntretien}\nLieu : {LieuEntretien}\n\nNous vous remercions de bien vouloir vous présenter à l'heure prévue.\n\nN'hésitez pas à nous contacter pour toute information complémentaire.\n\nCordialement,\n{NomEntreprise}",
                            EstActif = true,
                            Sujet = "Confirmation de votre entretien – {Poste}",
                            Type = "ConfirmationEntretien"
                        },
                        new
                        {
                            Id = 3,
                            Corps = "Bonjour {NomCandidat},\n\nNous avons le plaisir de vous informer que votre candidature pour le poste de {Poste} a été retenue avec succès.\n\nVotre profil a particulièrement retenu notre attention et correspond aux attentes du poste.\n\nNous vous contacterons prochainement afin de vous communiquer les prochaines étapes du processus.\n\nCordialement,\n{NomEntreprise}",
                            EstActif = true,
                            Sujet = "Félicitations – Votre candidature a été retenue – {Poste}",
                            Type = "Admission"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
